### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Yaurrdautia**
fixed the minor mistakes that were in the readme. I think this wasn't that important but just did it because it was nagging me.  
p.s. I heard you were releasing a new update. Are there any files that can be translated?

### CODE REVIEW

**Review by Starwort — CHANGES_REQUESTED** [review]
`power_team` and `power_pair` should be left as-is for consistency with both the English translation and the current Japanese translation. The rest of the changes are fine though

**Comment by Starwort** [comment]
Additionally, we have not yet finalised the translation files for spyke4 - I'll speak to the others and we'll see if we can get a translation channel for early-release files

**Comment by Yaurrdautia** [comment]
Ok, fixed

**Comment by Starwort** [comment]
Will merge now

**Pull request merged**
